# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  circleci_test:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - run: mvn install
    - run: mvn test

workflows:
  version: 2
  build:
    jobs:
      - circleci_test:
          filters:
            branches:
              only: circleci-project-setup